"""agrega sistema mas robusto al metodo de pago

Revision ID: ba9d963bff21
Revises: e8c4bcc2978e
Create Date: 2026-06-07 03:44:54.528323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba9d963bff21'
down_revision = 'e8c4bcc2978e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_externo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('ultimos_cuatro', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=20), nullable=True))
        batch_op.drop_column('detalles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodos_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalles', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('marca')
        batch_op.drop_column('ultimos_cuatro')
        batch_op.drop_column('token_externo')

    # ### end Alembic commands ###
